FROM node:24-alpine
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY index.html vite.config.ts tsconfig*.json eslint.config.js ./
COPY public ./public
COPY src ./src

EXPOSE 5173
CMD ["yarn", "dev", "--host", "0.0.0.0"]