FROM node:24-alpine AS build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY tsconfig.json ./
COPY src ./src
RUN yarn build --declaration false --declarationMap false --sourceMap false

FROM build AS dev
EXPOSE 3000
CMD ["yarn", "dev"]

FROM node:24-alpine AS prod
LABEL org.opencontainers.image.source=https://github.com/chazelm-balthazar/my-favorite-places
WORKDIR /app
ENV NODE_ENV=production
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production && yarn cache clean
COPY --from=build /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/index.js"]